// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA540QVLFacfZkKc1Z9YQDzc5PbQP6p2WU',
    appId: '1:456741749118:web:dd15650ede2d6d4a7eb32f',
    messagingSenderId: '456741749118',
    projectId: 'fitnes-66b28',
    authDomain: 'fitnes-66b28.firebaseapp.com',
    storageBucket: 'fitnes-66b28.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBtgJVUCk2S_mssABdRQSbSQiLfYORVy8',
    appId: '1:456741749118:android:8da6b98d6d2799187eb32f',
    messagingSenderId: '456741749118',
    projectId: 'fitnes-66b28',
    storageBucket: 'fitnes-66b28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBbi3aUWiYcaM-jLPL1HnsaDv2qwkEa94',
    appId: '1:456741749118:ios:872f3917bf5656247eb32f',
    messagingSenderId: '456741749118',
    projectId: 'fitnes-66b28',
    storageBucket: 'fitnes-66b28.firebasestorage.app',
    iosBundleId: 'com.fitova.fitness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBbi3aUWiYcaM-jLPL1HnsaDv2qwkEa94',
    appId: '1:456741749118:ios:872f3917bf5656247eb32f',
    messagingSenderId: '456741749118',
    projectId: 'fitnes-66b28',
    storageBucket: 'fitnes-66b28.firebasestorage.app',
    iosBundleId: 'com.fitova.fitness',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA540QVLFacfZkKc1Z9YQDzc5PbQP6p2WU',
    appId: '1:456741749118:web:2556b563e3ee4ce37eb32f',
    messagingSenderId: '456741749118',
    projectId: 'fitnes-66b28',
    authDomain: 'fitnes-66b28.firebaseapp.com',
    storageBucket: 'fitnes-66b28.firebasestorage.app',
  );
}
